# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f36c97741cd07f2091ed2ad759c0569ff0262aba8dc448d3071b37527e155d04aa59f241785bf707dbe60dbb7dad6463fb31898591217d22449271f72c1faeb

test:
  secret_key_base: 659f67924f80f4fb38fe9bbc5720db9ce3676ffd4d6ffe208dbd440c62a0950211383c4c4647d7087f473d0286248007452ce0918a09e66c005ab00441a7d505

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
